version: "3.8"

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_2TZzPg4dWuEF@ep-polished-lab-ajt0p5gl-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  postgres:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
